CSHA 	    SUBROUTINE WAVE
	    SUBROUTINE ELECT1
C CHECKED	
C		PERTURBATION TO AN ALPHA-CHAPMAN ELECTRON DENSITY MODEL 	

      COMMON /DDEBUG/ debug        
      COMMON /CONST/ PI,PIT2,PID2,DUM(5)	
      COMMON /XX/ MODX(2),X,PXPR,PXPTH,PXPPH,PXPT,HMAX	
      COMMON R(6) /WW/ ID(10),W0,W(400)	
      EQUIVALENCE (EARTHR,W(2)),(Z0,W(151)),(SH,W(152)),(DELTA,W(153)),
     1 (VSUBX,W(154)),(LAMBDAX,W(155)),(LAMBDAZ,W(156)),(TP,W(157))	
	   REAL LAMBDAX,LAMBDAZ	
CSHA Modified no PERT
      EQUIVALENCE (PERT,W(150))
CSHA	   DATA (MODX(2)=6H WAVE)
CHSA           MODX(2)= "WAVE "
	    

            PERT=0
            RETURN

       IF(X.EQ.0..AND.PXPR.EQ.0..AND.PXPTH.EQ.0..AND.PXPPH.EQ.0.)RETURN

	   IF (DELTA.EQ.0..OR.SH.EQ.0.) RETURN	

	   H=R(1)-EARTHR	
	   EXPQ=EXP(-((H-Z0)/SH)**2)	
	   TMP=PIT2*(TP+(PID2-R(2))*EARTHR/LAMBDAX+H/LAMBDAZ)	
	   SINW=SIN(TMP)	
	   COSW=SIN(PID2-TMP)	
	   CONS=1.0+DELTA*EXPQ*COSW	
      IF (H.NE.0.) PXPR=PXPR*CONS-X*DELTA*EXPQ*(2.0/SH**2*(H-Z0)*COSW	
     1    +PIT2/LAMBDAZ*SINW)	
	   PXPTH=PXPTH*CONS+X*DELTA*PIT2*EARTHR/LAMBDAX*SINW*EXPQ	
	   PXPPH=PXPPH*CONS	
	   PXPT=0.	

       IF(VSUBX.NE.0.) PXPT=-PIT2*VSUBX/LAMBDAX*X*DELTA*EXPQ*SINW	
       X=X*CONS	
       RETURN	
	   END 	

CP-135
